/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
  public String getGreeting() {
    return "Hello World!";
  }

  public static void main(String[] args) {
    System.out.println(new App().getGreeting());

    Calculate cal = new Calculate();
    int sum = cal.sum(2, 3);
    int sum_o = 0;
    int sum_e = 0;

    System.out.printf("Sum of 2 and 3 is %d. Average is %.1f%n", sum, cal.average(sum, 2));

    sum = cal.sigma(1, 10);
    System.out.printf("Sum of 1 to 10 is %d. Average is %.1f%n", sum, cal.average(sum, 10));

    sum_o = cal.sigmaOnlyOdd(1, 10);
    sum_e = cal.sigmaOnlyEven(1, 10);
    System.out.printf("Sum of odd of 1 to 10 is %d. Sum of even is %d.\n", sum_o, sum_e);
  }
}
